/*
-- Query: SELECT * FROM SupinBank.INTERESTPLAN
LIMIT 0, 1000

-- Date: 2012-02-25 21:28
*/
INSERT INTO `INTERESTPLAN` (`ID`,`NAME`) VALUES (1,'Current Account');
INSERT INTO `INTERESTPLAN` (`ID`,`NAME`) VALUES (2,'Savings Account');
INSERT INTO `INTERESTPLAN` (`ID`,`NAME`) VALUES (3,'Life Insurance');
INSERT INTO `INTERESTPLAN` (`ID`,`NAME`) VALUES (4,'First Home Saver Account');
